//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitf10a001_project_sign_up_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc
    {
        public acc()
        {
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string UserName { get; set; }
        public string pass { get; set; }
        public string mobile { get; set; }
    
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
