//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitf10a001_project_sign_up_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allad
    {
        public allad()
        {
            this.moredetails = new HashSet<moredetail>();
        }
    
        public int Id { get; set; }
        public string emailacc { get; set; }
        public string adtitle { get; set; }
        public string description { get; set; }
        public string price { get; set; }
        public string catagory { get; set; }
        public string postas { get; set; }
        public string condtion { get; set; }
        public string warranty { get; set; }
        public string adis { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public string mobile1 { get; set; }
        public string mobile2 { get; set; }
        public string date { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public string img4 { get; set; }
        public string time { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<moredetail> moredetails { get; set; }
    }
}
